@extends('layouts.app')

@section('content')
<!-- Defi-bank introduce -->
<section class="subPage">
    <div class="container">
        <h2 class="sectionHeading">Defi-bank 2.0 Introduce</h2>
        <p>Defi-Bank 2.0 functions include three main functions: Staking, Loans and Mortage. Staking function is implemented to pay interest to investors when depositing with term, interest is paid at the agreed rate by the Coin/Token kind that were deposited into Staking function and Coins/Tokens were donated by other projects; investors receive monthly interest in Coins/Tokens sent directly to their personal wallet on the first day of the next month and and receive both principal and interest in the last month. Loans function allows investors to pledge coins/tokens and can borrow a number of Coins/Tokens of the same kind or different types with the loan value not exceeding 50% of the market value of the pledged capital. Of course, the interest rate is calculated on a loan hourly basis and is notified in advance to investors and depends on the type of Coin/Token pledged or wanted to borrow. When the value of the loan is at an alarming level and there is not enough collateral, we will notify the investors that they need to add an additional mortgage by Coins/Tokens to the loan to maintain the loan position. If the risk ratio is not guaranteed, then the loan will be automatically liquidated and the loan amount returned with interest up to the time of loan repayment or when the loan is liquidated. Mortage function allows investors to borrow Coins/Tokens by pledging real life assets such as real estate ownership documents, written proof of assets licensed in each host country, and even other in-kind assets such as jewelry, vehicles and other high-value items with clear origin and the owners, our team will conduct a due diligence and offer a suitable loan and interest rate; we always look forward to working with reputable banks, insurance companies or chains of pawn shops and appraisal companies to develop this new trend together.</p>
        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-1.jpg') }}" alt="" class="img-thumbnail"></p>
        <p>In the current period, we have only implemented the Staking function, the Loans and Mortage functions will be implemented as soon as possible. Depending on each type of Coin/Token in order to have sources of interest payment for investors in line with the development orientation of each project, we will specifically publicize each Staking policy for each Coin/Token individually, details in the section <strong>"Defi-Bank 2.0 News"</strong>. Investment strategy that we recommend: <span class="fst-italic">Investors should carefully study the project well and long-term, with potential for future development to take advantage of the Staking function with the goal of compound interest of value. Coin/Token increases with the value of the project/business and the interest of the Staking function when buying and holding for a long time.</span></p>
        <p class="text-center fw-bold">The nine signs of a good project that we recommend are as follows:</p>
        <ul>
            <li class="mb-2">The <strong>development team's identity is public</strong>: The profile pictures are real and clear photos, not edited with any software, the information of the projects or companies that they have worked can be checked easily and have a wealth of experience in positions held in the project.</li>
            <li class="mb-2">The project development team <strong>directly responds to investor questions</strong> from time to time, which is announced in advance, in which the role of the CEO and official CMO of the project when answering questions of the investor, it is very important.</li>
            <li class="mb-2">The project puts the <strong>role of user account security on top</strong>, always pays attention to this issue and has an orientation to increase security in the general development process. Besides, the project also has a risk reserve fund to pay for the events of losing Coin/Token due to the project's security error, ensuring the interests of users.</li>
            <li class="mb-2">The project has a roadmap to bring the <strong>circulating supply of Coin/Token clearly and accurately</strong>. Ensure the correct number of notifications for each stage. The development team always comes up with solutions to minimize inflation in the ecosystem/project. To ensure this, after the circulating supply has been released to the community in sufficient quantity as announced by the project, the inflation rate of Coin/Token should be less than 2%/year or preferably does not increase the amount of circulating supply  in the community. Some projects have reported burning of circulating Coins/Tokens and there is evidence for this burning in a public, transparent and clear manner.</li>
            <li class="mb-2">The <strong>less strategic fundraising rounds</strong> of the project,  the better for the development. The quantity, the selling price for each round and the time of Coin/Token payment for each strategic investor or investment funds should be public, transparent and clear.</li>
            <li class="mb-2">The project development team needs to <strong>post pictures on the project's official social networking sites</strong> so that investors know that the development team is still following the roadmap and regularly updates the situation of the project for investors to know.</li>
            <li class="mb-2">The project's official coin/Token is <strong>used for a clear purpose</strong> in the ecosystem and has tends to gradually increase the need to hold or own for the purpose of achieving certain benefits in the system. Coin/Token is used to pay for the exchange of goods, information, and items in the ecosystem or to exercise a preferred option. In short, it must have a specific and practical meaning, for Coin of the platform needs to have obvious advantages over competitors such as faster speed, cheaper gas costs, higher security and other projects can build application chain easier and more diverse.</li>
            <li class="mb-2">The project's <strong>funding rounds are publicized</strong> with the selling price, results and specific use purposes of the raised capital for project construction and development, periodical reports on capital expenditure and construction results of respective products.</li>
            <li class="mb-2"><strong>Plans to increase the circulating supply</strong> in the community need to be announced on the project's official website <strong>at least six months</strong>, however, it is best for one year in advance for investors to have a plan for their investment in  a reasonable and mutually beneficial manner. These plans need to ensure clarity, transparency, publicity, accuracy and credibility.</li>
        </ul>				
        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-2.jpg') }}" alt="" class="img-thumbnail"></p>
        <p class="text-center fw-bold">Steps to participate in the Staking function in the project's ecosystem:</p>
        <ol>
            <li class="mb-2"><strong>Access the project's official KGD CEX application</strong>, this Dapp (can be downloaded from the link on the project's official website or search on the Appstore or Google Play, but we recommend downloading directly from the official website  of project to avoid impersonating dapps to scam). According to the project's Roadmap, we will launch the Alphatest version of KGD CEX in June-August 2022 (with main functions including Spot, P2P, Account information, Defi-Bank 2.0, Coinlaunch dapp).</li>
            <li class="mb-2">
                <p><strong>Log in</strong> with a shared account for the entire ecosystem, two-factor authentication (2FA) and go to Defi-Bank 2.0 on the main screen).</p>
                <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-3.jpg') }}" alt="" class="img-thumbnail"></p>
            </li>
            <li class="mb-2"><strong>Select the Coin/Token type</strong> for Staking and click to see details of staking packages. Each type of Coin/Token in the Defi-bank 2.0 wallet is sent from the Exchange wallet through the <strong>"Transfer"</strong> function. When users want to use Staking function with any type of Coin/token, they need transfer with that type. The number of Coins/Tokens shown on the screen is the total including not sending Staking and sending Staking Coins/Tokens. The number of Coins/Tokens that not sending Staking can be transferred back to the Exchange wallet through the <strong>"Transfer"</strong> function.</li>
            <li class="mb-2">
                <p class="fw-bold mb-2">Go to the detail screen for each type of Coin/Token:</p>
                <ul>
                    <li class="mb-2"><strong class="fst-italic">Red box 1</strong>: The ranking is numbered in the top 1500 of the most participants for Staking function, this leaderboard will have the privilege to buy ICOs of open-sale projects on the platform of the KGD ecosystem (ICO total sales of each project open for sale on the system is divided into three parts, of which two third are given priority to those in the top 1500 in order of priority from 1st place onwards until the priority number is exhausted; one third of the the remaining ICO total sales will be randomly selected for the winners of other participants for Staking function, the winning list of the purchased tickets will be published on the official website of the KGD ecosystem, only the information of the winning Usename).</li>
                    <li class="mb-2">
                        <p><strong class="fst-italic">Red box 2</strong>: the total number of Coin/Token that have not been sent to participate in Staking function, can be transferred to the Exchange wallet, but can also be used to participate in other Staking packages. The monthly interest of the Staking function will be transferred to this balance automatically on the first day of the following month.</p>
                        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-4.jpg') }}" alt="" class="img-thumbnail"></p>
                    </li>
                    <li class="mb-2">
                        <p><strong class="fst-italic">Red box 3</strong>: The monthly profit rate when sending for the Staking function with a 3-month term is calculated for each unit of Coin/Token, this rate may vary depending on the type of Coin/Token and details in the section <strong>"Defi-Bank 2.0 News"</strong>. In addition, there is a ratio of Coin/Token bonus sponsored by the project.</p>
                        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-5.jpg') }}" alt="" class="img-thumbnail"></p>
                    </li>
                    <li class="mb-2"><strong class="fst-italic">Red box 4</strong>: Monthly rate of interest when depositing for Staking function with 6-month, 1-year or 2-year term compared to 3-month term deposit to partake in the Staking. This ratio is agreed upon by the KGD ecosystem and the project's DEV team and to be announced on <strong>"Defi-Bank 2.0 News"</strong> section.</li>
                    <li class="mb-2"><strong class="fst-italic">Red box 5</strong>: Including terms when participating in the Staking function as 3-month term, 6-month term, 1-year term and 2-year term. However, the monthly interest is paid into Defi-Bank wallet but the contributed capital for Staking is paid in the last month of the deposit term and is not withdrawn during the process.</li>
                    <li class="mb-2"><strong class="fst-italic">Red box 6 and 7</strong>: Details of all Staking deposits include full information about the number of Coins/Tokens to be sent to participate, the total amount received back, the received amount of Coins/Tokens, start time, end time, Details of all monthly amount and time to be received back and Coin/Token bonus.</li>
                </ul>
            </li>
            <li class="mb-2">
                <p>When clicking to select the participating Staking package, users will see a Staking interface and details the monthly interest payment time, enter the amount that you want to send and press the "Accept" button to participate. Two-factor authentication “2FA” is required to ensure investment decision. Note: The starting month to be calculated interest payment is from the following month  of registration and accepting for Staking package, so it is recommended to register for the Staking package at the end of each month instead of at the begining of each month.</p>
                <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-6.jpg') }}" alt="" class="img-thumbnail"></p>
            </li>
            <li class="mb-2">
                <p>Users can transfer Coin/Token between Defi-Bank 2.0 wallet and Exchange wallet easily without any fees through the <strong>"Transfer"</strong> section.</p>
                <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-7.jpg') }}" alt="" class="img-thumbnail"></p>
                <p>And see the history of transfers between the two wallets using the transaction history on the Transfer interface.</p>
                <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-8.jpg') }}" alt="" class="img-thumbnail"></p>
                <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-introduce-9.jpg') }}" alt="" class="img-thumbnail"></p>
            </li>
        </ol>
    </div>
</section>
@endsection
