@extends('layouts.app')

@section('content')
<!-- Social Introduce -->
<section class="subPage">
    <div class="container">
        <h2 class="sectionHeading">Coinlaunch Introduce</h2>
        <p class="text-center"><img src="{{ asset('img/subpage/coinlaunch-introduce-1.jpg') }}" alt="" class="img-thumbnail"></p>
        <p>Coinlaunch creates a potential market for the DEV team and investors, the DEV team who wants to sell their project has more funding to continue the project stages, perfects the product and has more motivation to develop the project. Investors can buy Coin/Token of the project at an early stage and with the potential for higher interest in the future.</p>
        <p>Projects that are opened for ICO sale on the KGD Coinlaunch platform will be carefully evaluated by experts from the KGD team for the project's information. We understand that these may affect the reputation of the project participating in Coinlaunch in particular and the KGD ecosystem in general.Investment strategy that we recommend: <span class="fst-italic">Investors should carefully study the project well and long-term, with potential for future development to take advantage of the Staking function with the goal of compound interest of value. Coin/Token increases with the value of the project/business and the interest of the Staking function when buying and holding for a long time.</span></p>
        <p class="fw-bold text-center">The nine signs of a good project that we recommend are as follows:</p>
        <ul>
            <li class="mb-2">The <strong>development team's identity is public</strong>: The profile pictures are real and clear photos, not edited with any software, the information of the projects or companies that they have worked can be checked easily and have a wealth of experience in positions held in the project.</li>
            <li class="mb-2">The project development team <strong>directly responds to investor questions</strong> from time to time, which is announced in advance, in which the role of the CEO and official CMO of the project when answering questions of the investor, it is very important.</li>
            <li class="mb-2">The project puts the <strong>role of user account security on top</strong>, always pays attention to this issue and has an orientation to increase security in the general development process. Besides, the project also has a risk reserve fund to pay for the events of losing Coin/Token due to the project's security error, ensuring the interests of users.</li>
            <li class="mb-2">The project has a roadmap to bring the <strong>circulating supply of Coin/Token clearly and accurately</strong>. Ensure the correct number of notifications for each stage. The development team always comes up with solutions to minimize inflation in the ecosystem/project. To ensure this, after the circulating supply has been released to the community in sufficient quantity as announced by the project, the inflation rate of Coin/Token should be less than 2%/year or preferably does not increase the amount of circulating supply  in the community. Some projects have reported burning of circulating Coins/Tokens and there is evidence for this burning in a public, transparent and clear manner.</li>
            <li class="mb-2">The <strong>less strategic fundraising rounds</strong> of the project,  the better for the development. The quantity, the selling price for each round and the time of Coin/Token payment for each strategic investor or investment funds should be public, transparent and clear.</li>
            <li class="mb-2">The project development team needs to <strong>post pictures on the project's official social networking sites</strong> so that investors know that the development team is still following the roadmap and regularly updates the situation of the project for investors to know.</li>
            <li class="mb-2">The project's official coin/Token is <strong>used for a clear purpose</strong> in the ecosystem and has tends to gradually increase the need to hold or own for the purpose of achieving certain benefits in the system. Coin/Token is used to pay for the exchange of goods, information, and items in the ecosystem or to exercise a preferred option. In short, it must have a specific and practical meaning, for Coin of the platform needs to have obvious advantages over competitors such as faster speed, cheaper gas costs, higher security and other projects can build application chain easier and more diverse.</li>
            <li class="mb-2">The project's <strong>funding rounds are publicized</strong> with the selling price, results and specific use purposes of the raised capital for project construction and development, periodical reports on capital expenditure and construction results of respective products.</li>
            <li class="mb-2"><strong>Plans to increase the circulating supply</strong> in the community <strong>need to be announced</strong> on the project's official website <strong>at least six months</strong>, however, it is best for one year in advance for investors to have a plan for their investment in  a reasonable and mutually beneficial manner. These plans need to ensure clarity, transparency, publicity, accuracy and credibility.</li>
        </ul>
        <p class="text-center"><img src="{{ asset('img/subpage/coinlaunch-introduce-2.jpg') }}" alt="" class="img-thumbnail"></p>
        <p>Projects want to open ICO sale on KGD coinlaunch platform, we are honored to be trusted by the project, please contact with us via email of KGD ecosystem: <a href="mailto:kingofgameanddex86@gmail.com" class="text-primary">kingofgameanddex86@gmail.com</a></p>
    </div>
</section>
@endsection
