@extends('layouts.app')

@section('content')
<!-- KGD Staking -->
<section class="subPage">
    <div class="container">
        <h2 class="sectionHeading">KGD Staking</h2>
        <h5>1. Defi-Bank Fund 2.0</h5>
        <p>According to the project's KGD token distribution, we have absolutely no funds from the total supply to pay for the Staking function, which helps to keep the amount of KGD tokens from being inflated, so the value of KGD tokens will be tends to stabilize and increase in proportion to the value of the business.</p>
        <p>The payment fund for the Staking function is extracted from the transaction fees of all games (20% of the total transaction fees) and the KGD centrelized exchange, Socialfi social network (10% of the total transaction fees). Gamefi transaction fees include NFT item transaction fees between players and revenue for sales of limited additional NFT items to players.</p>
        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-news-kdg-staking-1.jpg') }}" alt="" class="img-thumbnail"></p>
        <p>The transaction fee of the KGD exchange and of the Socialfi social network is the fee for exchanging NFT items or products between users.</p>
        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-news-kdg-staking-2.jpg') }}" alt="" class="img-thumbnail"></p>
        <h5>2. Distribution of KGD</h5>
        <p class="text-center"><img src="img/subpage/news-kgd-coin-info-11.jpg" alt="" class="img-thumbnail"></p>
        <ul>
            <li class="mb-2">February 2022: Starting official account registration, each account registered in the first 15,000 users and successful KYC will be rewarded with 1 KGD immediately paid to the personal wallet of the KGD ecosystem, and 1000 KNB paid to the Games wallet when the official version of Avengers games is officially released. Users from 15,001 onwards are only rewarded with KNB tokens according to the respective levels.</li>
            <li class="mb-2">March 2022: Conducting an ICO sale, depending on the level of ICO purchase, the corresponding KGD token will be rewarded, KGD will be sent to the personal wallet in the system after buying the ICO. KNB is paid to Games wallet when the official version of Avengers games is officially released. According to calculations, the largest amount of KGD bonus for the ICO is 30,000 KGD. ICO selling price is $0.15 / 1 KGD. Total amount is 5,000,000 KGD; however, locked for 3 months after the first IEO on CEX, scheduled for June 2022. After that, each month, the buyer is paid with 10% of bought KGD amount until the purchase quantity is completed.</li>
            <li class="mb-2">April 2022: According to the plan to conduct IDO on Pancakeswap, the quantity is 2,000,000 KGD, the selling price is $0.60/ 1KGD, DEV team commits not to sell more quantity, and guarantees the IDO selling price above 0.60$.</li>
            <li class="mb-2">June-July 2022: IEO on CEX  has been contacted and approved by a number of partners when all necessary conditions are accepted such as ONUS, MEXC, GATE, HUOBI, HOTBIT, BYBIT and BINANCE Exchange. IEO selling price is $0.75, IEO selling quantity is 40,000,000 KGD.</li>
            <li class="mb-2">September-October 2022: Start paying for the ICO round, each month paying a total of 500,000 KGD to buyers and will be sent to personal wallets on the ecosystem. July 2023: Complete the paying to the buyers.</li>
            <li class="mb-2">August 2023: Start paying angel investors 600,000 KGD/month; and a total of 6,000,000 KGD paid to investors, 10% per month until paid off. June 2024 will complete the payment of KGD tokens to angel investors.</li>
            <li class="mb-2">From July 2024 onwards: Each month can sell to the CEX under 12,000 KGD to upgrade the system, improve security and build new games for the ecosystem or pay for the game leaderboard or ranks. However, if the level of deduction from the transaction fees of the exchanges is enough to ensure this payments, they will commit not to sell even 1 KGD of tokens. The bonus and development funds are extracted from the transaction fees on the KGD CEX exchange and the trading fees on the Marketplace of the games in the ecosystem. We commit that any selling or bying related to the circulating supply of KGD tokens will be announced at least 6 months in advance on the official website and the project's periodic reports every 3 months; Every 6 months and once a year. We understand that limiting inflation is always a consideration in the future.</li>
            <li class="mb-2">From January 2025 onwards: We will extract the rate of 10-15% of the revenue from the transaction fees on the KGD CEX exchange and the trading fees on the Marketplace of the games in the ecosystem to buy back KGD circulate and burn it by sending it to a non-existent wallet address and locking it forever to reduce the circulating supply in the market.</li>
            <li class="mb-2">From January 2027 onwards: We re-evaluate the ecosystem that has stable revenue, enough costs for ecosystem activities, we proceed to burn all the remaining KGD tokens by sending to a non-existent wallet address and permanently locked in order to reduce or remain the circulating supply in the market. So we commit to do with all the credit of the project and the company.</li>
        </ul>
        <h5>3. Benefits of Staking</h5>
        <ul>
            <li class="mb-2">The mechanism of the interest rate according to the transaction fees that create the Staking Fund will promote the value of KGD tokens due to the limitation of circulating supply to the community, this fund will gradually increase according to the number of monthly users and ensure the Coin/Token Staking to be very safe.</li>
            <li class="mb-2">In addition to the main Coin/Token to pay for the interest, Staking function users are also given other Coins/Tokens including KNB tokens that can be used in all games, and <strong>valuable Coins/Tokens</strong> that have other roles provided and guaranteed by the project.</li>
            <li class="mb-2">The ranking is numbered in the top 1500 of the most participants for Staking function, this leaderboard will have the <strong>privilege to buy ICOs</strong> of open-sale projects on the platform of the KGD ecosystem (ICO total sales of each project open for sale on the system is divided into three parts, of which two third are given priority to those in the top 1500 in order of priority from 1st place onwards until the priority number is exhausted; one third of the the remaining ICO total sales will be randomly selected for the winners of other participants for Staking function, the winning list of the purchased tickets will be published on the official website of the KGD ecosystem, only the information of the winning Usename).</li>
            <li class="mb-2">Staking users have the right to vote on decisions related to the issuance of more KGD tokens from the remaining supply. implementation for voting is done through the Defi-Bank 2.0 function.</li>
        </ul>
        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-news-kdg-staking-4.jpg') }}" alt="" class="img-thumbnail"></p>
        <h5>4. Monthly ratio of Staking Fund</h5>
        <p class="text-center"><img src="{{ asset('img/subpage/defi-bank-news-kdg-staking-5.jpg') }}" alt="" class="img-thumbnail"></p>
        <ul>
            <li class="mb-2">The last day of the month (00.00.00 GMT time the first day of the next month) will determine the amount of KGD Staking allocated for the next month (so if deposited into Staking on any day of the month, beginning interest is paid from the following month).</li>
            <li class="mb-2">The 3-month term is calculated as the rate of 100%; 6-month term, 1-year term and 2-year term are refunded with a higher interest rate than 3-month term (this rate is public for each type of Coin/Token; example KGD figure, depositing into 6 month package, will be received an interest rate of 120% (equivalent to 1.2 times) compared to the 3-month package; 1-year depositing package will be received an interest rate of 150 % (equivalent to 1.5 times) compared to the 3-month package; 2-year epositing package will be received interest 180 % (corresponding to 1.8 times) compared to the 3-month package). Thus, the longer the deposit period, the more profitable it is.</li>
            <li class="mb-2">Total amount of KGD staking interest distribution is calculated as follows: Total amount of staking = Total amount of 3-month term + Total amount of 6-month term x 1.2 + Total amount of 1-year term x 1.5+ Total amount of 2 year term x 1.8; for example: At 00.00.00 GMT on the first day of the next month, deciding on the amount of the previous month's deposit of all terms: Total amount of 3 month term: 10,000,000 KGD; Total amount of 6 month term: 5,000,000 KGD; Total amount of 1 year term: 2,000,000 KGD; Total amount of 2 year term: 1,000,000 KGD; according to the calculation formula, Total KGD staking = 20,800,000 KGD.</li>
            <li class="mb-2">Supposing for the Staking Fund of the next month that is 30,000,000 KGD (because all transactions in the ecosystem use KGD as a payment unit and pay for transaction fees).</li>
            <li class="mb-2">Interest rate for 1 KGD deposited into the Staking function for a 3-month term = 30,000,000/20,800,000 = 1.4423076923 (taken 10 digits after the comma, no rounding); So, for every 3 month term of 1 KGD for Staking in the previous month, the next month will be received 1.4423076923 KGD (in addition to the principal amount that it will be fully returned in the last month and attached with the last month's interest rate). This rate changes in a monthly manner  depending on the Staking Fund obtained during the month.</li>
            <li class="mb-2">Interest rate for 6-month term = 1.2 x 3-month term interest rate = 1.7307692308; 1-year term interest rate = 1.5 x 3-month term interest rate = 2.1634615384; Interest rate for 2-year term = 1.8 x 3-month interest rate = 2.5961538461. <span class="text-danger"><span class="fst-italic">Note that:</span> In addition, there are also monthly bonuses for other Coins/Tokens, so partaking in the staking function has a lot of benefits for users.</span></li>
        </ul>
    </div>
</section>
@endsection
