@extends('layouts.app')

@section('content')
    <!-- news analysis -->
    <section class="subPage">
        <div class="container">
            <h2 class="sectionHeading">BTC, ETH, BNB, KGD analysis</h2>
            <h3 class="text-center mb-4">TREND PREDICTION 2022-2027</h3>
            <h5>I. BTC Analysis</h5>
            <p>In 2009, after the time when the housing market collapsed and led to the global economic crisis, a mysterious figure until now using the pseudonym "Satoshi Nakamoto" wrote his idea on a document. The so-called whitepaper on digital assets can bring transaction costs much cheaper than what we pay for sending and receiving currency through money management institutions.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-1.jpg') }}" alt="" class="img-thumbnail"></p>
            <h6>2009-2015 stage</h6>
            <p>Bitcoin is priced at $0.0076/BTC - This is calculated by the electricity cost of a computer to mine Bitcoin when it was introduced in 2009. On July 17, 2010, BTC increased to $0.09. April 13, 2011 Bitcoin price rebounded from $1 to a peak of $29.60 on June 7, 2011, up 2,960% within three months. This was followed by a sharp crypto market downturn and Bitcoin price bottoming at $2.05 in mid-November. In 2012, BTC increased from $4.85 (May 9) to $13.5 (August 2015). In 2013 BTC was trading around $13.28 and hit $230 on April 8, 2013. A rapid price drop was followed. At the beginning of October 2013, Bitcoin was trading at $123. By December, BTC spiked to $1,237 and dropped to $687 three days later. The price of Bitcoin fell throughout 2014 and hit $315.21 in early 2015.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-2.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>BTC price grew steadily in 2016 to $900 by the end of 2016. During 2017, Bitcoin's price hovered around $1,000 until it spiked to $19,345. At that time, Bitcoin started to receive great attention. And other organizations started to develop other Crypto projects to compete with Bitcoin. In 2018, Bitcoin dropped more than 80% and fell to the $3,000 level. In 2020, the shutdown of the economy due to the COIVD -19 pandemic, the shutdown and government policies have raised concerns among investors about the global economy about inflation. Since then, it has accelerated the rise of Bitcoin to the present time. 2020 can be considered a boom year for BTC. After the correction from $10,000 to below $4,000 (March 2020), Bitcoin started its strong bull cycle and reached an ATH at $69,000 - with an x18x gain. Let's take a look back at some of the prominent events that had a direct impact on the price of Bitcoin at the time.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-3.jpg') }}" alt="" class="img-thumbnail"></p>
            <h6>Special events</h6>
            <p>In August 2020, MicroStrategy invested $250 million in Bitcoin as a reserve asset. In October 2020, Square, Inc. invest about 1% of total assets ($50 million) buying Bitcoin. In November 2020, PayPal announced that US users could buy, hold, or sell Bitcoin. On November 30, 2020, the bitcoin value hit a new all-time high of $19,860. Alexander Vinnik - the founder of BTC-e was convicted and sentenced to 5 years in prison for money laundering in France. In December 2020, Massachusetts Mutual Life Insurance Company announced a $100 million Bitcoin purchase - or 0.04% of its investment assets. On January 19, 2021, Elon Musk repeatedly shared about Bitcoin on his Twitter. This caused BTC to rapidly increase around 5,000 prices in 1 hour to $37,299. On January 25, 2021, Microstrategy announced that it would continue to buy Bitcoin, bringing the amount of Bitcoin it holds to $2.38 billion. On February 8, 2021, Tesla announced $1.5 billion worth of Bitcoin purchases and plans to start accepting Bitcoin for transportation payments, pushing the Bitcoin price to $44,141. In September 2020, the Canton of Zug, Switzerland announced that it would begin accepting tax payments in Bitcoin in February 2021. In June 2021, the Legislative Assembly of El Salvador voted to pass a law to make Bitcoin legal tender in El Salvador. Also in June, a Taproot software upgrade was approved, adding support for Schnorr signatures, improving the functionality of Smart Contracts and the Lightning Network. This upgrade was installed in November. On October 16, 2021, the SEC approved the ProShares Bitcoin Strategy ETF - a cash-settled futures exchange-traded fund.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-4.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>Cash flow into the crypto market has increased 10 times from 2020 -2022, shown on the chart of Total Market Capitalization (TMC), in 2020, TMC is only at 250B$, by 2022, reached a new high (ATH) is 2.75T$. In the past, 2018 also peaked (ATH) and corrected in 2 years 2018-2020, so in the period of 2022-2024, further correction may be needed, level 1 TMC adjustment, support point 1.7T$. Adjustment level 2 TMC 1-1.25T$, this adjustment is necessary to attract new cash flow to Crypto market, compared to other financial markets, TMC of Crypto market is very small, and this is also This is an opportunity for investors to get in early and invest for the long term.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-5.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>BTC total market capitalization is similar to TMC, increasing 10 times between 2020-2022, and is correcting the support level of $950B. Lower support on the chart is at 650B$, BTC needs to retest BTC TMC support at 950B$.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-6.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>On the chart of Total Market Capitalization Dominance (%), BTC is returning to 2018 levels (40%). The regular cash flow will return to BTC similar to the period 2018-2021 for the period 2022-2025. Along with the steadily growing rate of ETH Dominance over the years, it shows that the trend of money flow always believes in the ecosystem of ETH.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-7.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>BTC/USDT price pair at the weekly candlestick shows that the BTC price has increased very strongly and rapidly in the period of 2020-2022, specifically, increasing 10 times in 1-2 years. Correction is needed to shake off short-term and retail investors before a new ATH pops up.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-8.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>The sentiment index in the monthly candlestick shows that in the long term, investors still believe in the development of BTC in particular and the Crypto market in general. The buying index still dominated despite strong corrections of the market.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-9.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>The weekly price of BTC/USDT shows that BTC price has gone below MA 50, as a rule in the past, there is a high probability that BTC price will retest the MA200 in the next 1-2 years. However, the indicator on the chart shows that in the long term, the BTC price is still on the rise from 2022-2027.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-10.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>According to the weekly candle chart, BTC price is correcting and retesting the $28,000 -30,000 level; In the short-term next 1-4 months. February 2022-June 2022, BTC price has two directions in price: A successful retest of the $45,374 resistance will confirm a new bull cycle to the price area of 65,000; in case of a failed retest of the resistance at $45,374; a return to test the lower supports at $38,390; $27,796 and $21,108. However, as it is analyzed above, this adjustment is necessary after a very strong and fast growth in the past period.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-11.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>The $28,000-30,000 support was retested in July 2021; so this is strong enough support to halt BTC's price drop, the upward trend somewhat overpowered the trend to retest lower prices. We are also bullish on the market and believe in a new cyclical uptrend in the period 2022-2027, and hit a new BTC ATH of $180,000-200,000 in this period.</p>
            <h5>II. ETH Analysis</h5>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-12.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>Cash flow into the ETH ecosystem in the 2016-2021 period is strong and sustainable, which makes the ETH value increase more than 10 times in the short period of 2020-2022. The level 1 support at $2000 was quite stiff, the deep support at $1650 was successfully held in July 2021. The rapid growth in a short time is similar to BTC, there should be a reasonable correction in 2022 before breaking out to a new ATH in the period of 2023-2027.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-13.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>Regarding the long-term trend of ETH, it is still in the long-term uptrend channel, but alternating with short-term price increases, it takes time to eliminate retail investors before going to a new ATH. However, the gas fee of the ETH ecosystem is a difficult issue that hinders the application expansion of the ecosystem in the future.</p>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-14.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>In the short term 2022-2023, ETH can reach the intermediate resistance at $3923-$4000 and retest the below support line of the bullish channel in the $2800-3000 zone. In the period of 2023-2027, we believe in the sustainable growth of ETH and the outstanding improvements of the development team, possibly to a new ATH of $8000-10000.</p>
            <h5>III. BNB Analysis</h5>
            <p class="text-center"><img src="{{ asset('img/subpage/news-analysis-15.jpg') }}" alt="" class="img-thumbnail"></p>
            <p>Similar to ETH, the BNB ecosystem in particular and the BSC system in general are attracting large and stable cash flows. With a diverse ecosystem and low gas fees, fast speed, BSC system is an incubator for projects. Therefore, the demand to use BNB will increase more and more, BNB is being improved with an automatic and periodic coin burning policy, the possibility of price increase is very high. BNB is having a much-needed correction after a short and strong bullish period 2020-2022. The $300-330 support is held and the bullish channel is still warranted, we believe that BNB will reach a new ATH of $1000-1500 during 2023-2027.</p>
            <p class="text-danger">Risk warning: Cryptocurrency trading is subject to high market risk. Please make your trades cautiously. You are advised that we are not responsible for your trading losses</p>
            <p class="text-center">KGD team <span class="fst-italic">(synthesis and analysis)</span></p>
        </div>
    </section>
@endsection
